package com.example.exercise2.model

data class Shop(
    val address: String,
    val administratorsIds: Any,
    val averageRating: Double,
    val backgroundImageThumbUrl: Any,
    val backgroundUrl: String,
    val categoriesCount: Int,
    val channel: Any,
    val deliveryFee: Double,
    val deliveryFeeType: Int,
    val description: String,
    val distance: String,
    val estimatedTime: String,
    val expressProductsLimit: Int,
    val expressRadius: Any,
    val hasExpressDelivery: Boolean,
    val hasNewStyleCategory: Boolean,
    val haveService: Boolean,
    val id: Int,
    val isActive: Boolean,
    val isFree: Boolean,
    val isShopOpen: Boolean,
    val lastActivityDate: Any,
    val latitude: Double,
    val logoImageThumbUrl: Any,
    val logoUrl: String,
    val longitude: Double,
    val lowerLimit: Double,
    val name: String,
    val orderNo: Int,
    val reviewsCount: Int,
    val shopEmail: Any,
    val shopPhone: Any,
    val userPromoCode: Any,
    val workingHours: List<WorkingHour>
)